Add vector norm example (DMA streaming + AIE)
esa-tu-darmstadt/tapasco-examples pull request #2
Opened 2024-10-10 14:44 UTC by tsmk94

2024-10-30 10:22 UTC, yannickl96 requested changes
Nice example! I used Vivado 2023.1 and tested it on the VCK5000 and everything appears to work as expected. I just have some minor requests.

2024-10-30 10:22 UTC, yannickl96 commented on Vector-Norm/README.md
> +- The PE is written in Bluspec SystemVerilog (BSV), make sure the [BSV compiler](https://github.com/B-Lang-org/bsc) `bsv` is installed.
```suggestion
- The PE is written in Bluspec SystemVerilog (BSV), make sure the [BSV compiler](https://github.com/B-Lang-org/bsc) `bsc` is installed.
```

2024-10-30 10:22 UTC, yannickl96 commented on .gitmodules
> +	url = https://github.com/esa-tu-darmstadt/BlueAXI.git
We already have several paths to the same submodules. Wouldn't it be easier at this point to just clone the submodules once and have the individual example build scripts create symlinks for BSVTools? Otherwise you get the same files over and over again for each example.

2024-10-30 10:22 UTC, yannickl96 commented on Vector-Norm/README.md
> +Run `source tapasco-setup.sh` in your TaPaSCo workspace and build the runtime using `tapasco-build-libs`. Make sure *CMake* and *Boost (program options)* are installed. Then build the software with `
For people who did not install TaPaSCo manually first, but relied on the ``build_bitstream.sh``-script, the ``tapasco-build-libs`` may complain about ``cargo`` not being found. Maybe add a short summary of building the TaPaSCo runtime here, including dependency installation?

2024-10-30 10:22 UTC, yannickl96 commented on Vector-Norm/vector-norm.json
Can you guide people a little bit more through this file, e.g., by using a dedicated section in the README?

2024-10-30 10:22 UTC, yannickl96 commented on Vector-Norm/sw/C++/main.cpp
Could you write a short paragraph in the READMe about the important TaPaSCo things done in this file? E.g., stream creation and the structure of the launch call?

2024-10-30 16:00 UTC, tsmk94 commented on Vector-Norm/README.md
> +Run `source tapasco-setup.sh` in your TaPaSCo workspace and build the runtime using `tapasco-build-libs`. Make sure *CMake* and *Boost (program options)* are installed. Then build the software with `
Adressed in [fbf8fb4](https://github.com/esa-tu-darmstadt/tapasco-examples/pull/2/commits/fbf8fb4f1430f49e217581ff10c6f2a93e3042d2)

2024-10-30 16:00 UTC, tsmk94 commented on Vector-Norm/vector-norm.json
Adressed [fbf8fb4](https://github.com/esa-tu-darmstadt/tapasco-examples/pull/2/commits/fbf8fb4f1430f49e217581ff10c6f2a93e3042d2)

2024-10-30 16:00 UTC, tsmk94 commented on Vector-Norm/sw/C++/main.cpp
[fbf8fb4](https://github.com/esa-tu-darmstadt/tapasco-examples/pull/2/commits/fbf8fb4f1430f49e217581ff10c6f2a93e3042d2)

2024-10-31 07:13 UTC, tsmk94 commented on .gitmodules
> +	url = https://github.com/esa-tu-darmstadt/BlueAXI.git
Thanks for the hint. I added a separate directory for the two libraries and created symlinks in the respective subdirectories of the BSV cores, so we only have BlueAXI/Lib once as submodule. See [d7cff65](https://github.com/esa-tu-darmstadt/tapasco-examples/pull/2/commits/d7cff655f331ae5f0b6bdb80b7b3f01c995544c3).

2024-11-01 17:29 UTC, yannickl96 reviewed
Just a small typo in the README. Thanks for the detailed explanations!

2024-11-01 17:29 UTC, yannickl96 commented on Vector-Norm/README.md
> +For the `DMA-Streaming` feature we need to specify the interface ports used for the host-to-device and device-to-host streams. Note that only one stream in each direction is currently suppoerted by T
```suggestion
For the `DMA-Streaming` feature we need to specify the interface ports used for the host-to-device and device-to-host streams. Note that only one stream in each direction is currently supported by TaPaSCo.
```

2024-11-01 17:31 UTC, yannickl96 approved these changes
LGTM now!

2024-11-03 17:14 UTC, merged